# fly.toml app configuration file generated for backend-dawn-glade-9209 on 2024-07-01T16:45:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-dawn-glade-9209'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
